### ISSUE TITLE
simpledorff not importing

### ISSUE THREAD

**Issue by nikmart** [LightTag/simpledorff#2]
Hi there!

Thank you for creating this python module for Krippendorff's Alpha. I am trying to install and use, but am running into issue on both my Mac (Catalina) with `conda` and on my Linux (Ubuntu 18.04) box with `pip` where it installs but cannot be imported.

The module seems to install on both system fine with `pip install simpledorff`

[Mac - Conda]
```shell
(inagt) ~ conda list | grep simpledorff
simpledorff               0.0.1                    pypi_0    pypi

Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import simpledorff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'simpledorff'
```
[Linux - virtualenv]
```shell
(inagt) nik@pitts:~$ pip list | grep simpledorff
simpledorff        0.0.1

Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simpledorff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'simpledorff'
```

Any ideas what could be going wrong? I have seen issues with permissions or pip installing into the wrong location, but everything there seems to be in order....

Thank you!

**Comment by talolard** [comment]
Hi, this is fixed. 
just do
```
pip install -U simpledorff 
```
